listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
autosave_interval 60
autosave_on_changes false

log_dest stdout
log_timestamp true
connection_messages true
